title: Data Capsule Appliance

# For development purposes. Please make sure this is commented out before committing. 
#baseurl: "/data-capsule-appliance"


# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed