title: Data Capsule Appliance
#baseurl: "/home"
#url: "https://data-to-insight-center.github.io"

#baseurl: ""
#url: "http://localhost"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed