title: Data Capsule Appliance
baseurl: "/data-capsule-appliance"
url: "https://data-to-insight-center.github.io"

#baseurl: ""
#url: "http://localhost:4000"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed